config/routes.rb
Rails.application.routes.draw do
  devise_for :admin
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'welcome/index'
  get 'programming/index'
  get 'programming/ruby'
  get 'programming/java'
  get 'programming/python'
  get 'music/index'
  get 'music/prehistory'
  get 'music/godfathers'
  get 'music/old_nectar'
  get 'music/svetlo'
  get 'music/pinstripe'
  get 'music/ten_thousand_microphones'
  get 'music/solo_music'
  get 'literature/index'
  get 'literature/prose'
  get 'literature/poetry'
  get 'literature/lyrics'
  get 'literature/dramaturgy'
  get 'nowhereland/index'
  get 'nowhereland/history'
  get 'nowhereland/cartography'
  get 'nowhereland/languages'
  get 'nowhereland/folklore'
  get 'contacts/index'
  get 'search/index'

  root 'welcome#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # before_action :authenticate_admin!

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/album.rb
class Album < ActiveRecord::Base
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/section.rb
class Section < ActiveRecord::Base
  scope :programming, -> { find_by name: 'programming' }
  scope :music,       -> { find_by name: 'music'       }
  scope :literature,  -> { find_by name: 'literature'  }
  scope :nowhereland, -> { find_by name: 'nowhereland' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
  end
end

app/controllers/literature_controller.rb
class LiteratureController < ApplicationController

  before_filter :sections_definition

  def index
  end

  def prose
    @description = Section.find_by(name: 'prose').description
  end

  def poetry
    @description = Section.find_by(name: 'poetry').description
  end

  def lyrics
    @description = Section.find_by(name: 'lyrics').description
  end

  def dramaturgy
    @description = Section.find_by(name: 'dramaturgy').description
  end

  private

  def sections_definition
    @section = Section.literature
    @sub_sections = Section.where( parent_section: @section.id )
  end

end

app/controllers/music_controller.rb
class MusicController < ApplicationController

  before_filter :sections_definition

  def index
  end

  def prehistory
    @description = Section.find_by(name: 'prehistory').description
  end

  def godfathers
    @description = Section.find_by(name: 'godfathers').description
  end

  def old_nectar
    @description = Section.find_by(name: 'old_nectar').description
  end

  def svetlo
    @description = Section.find_by(name: 'svetlo').description
  end

  def pinstripe
    @description = Section.find_by(name: 'pinstripe').description
  end

  def ten_thousand_microphones
    @description = Section.find_by(name: 'ten_thousand_microphones').description
  end

  def solo_music
    @description = Section.find_by(name: 'solo_music').description
  end

  private

  def sections_definition
    @section = Section.music
    @sub_sections = Section.where( parent_section: @section.id )
  end

end

app/controllers/nowhereland_controller.rb
class NowherelandController < ApplicationController

  before_filter :sections_definition

  def index
  end

  def history
    @description = Section.find_by(name: 'history').description
  end

  def cartography
    @description = Section.find_by(name: 'cartography').description
  end

  def languages
    @description = Section.find_by(name: 'languages').description
  end

  def folklore
    @description = Section.find_by(name: 'folklore').description
  end

  private

  def sections_definition
    @section = Section.nowhereland
    @sub_sections = Section.where( parent_section: @section.id )
  end

end

app/controllers/programming_controller.rb
class ProgrammingController < ApplicationController

  before_filter :sections_definition

  def index
  end

  def ruby
    @description = Section.find_by(name: 'ruby').description
  end

  def java
    @description = Section.find_by(name: 'java').description
  end

  def python
    @description = Section.find_by(name: 'python').description
  end

  private

  def sections_definition
    @section = Section.programming
    @sub_sections = Section.where( parent_section: @section.id )
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/literature_helper.rb
module LiteratureHelper
end

app/helpers/music_helper.rb
module MusicHelper
end

app/helpers/nowhereland_helper.rb
module NowherelandHelper
end

app/helpers/programming_helper.rb
module ProgrammingHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="favicon.ico">

    <title>Полное собрание сочинений Игоря Клекотнева</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="http://bootstrap-3.ru/assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <%= csrf_meta_tags %>
  </head>

  <body>

    <div class="container">

      <div class="main-menu">
        <div class="inner">
          <% site_header = "<h1 class=\"cover-heading\">Полное Собрание Сочинений Игоря Клекотнева</h1>" %>
          <%= link_to site_header.html_safe, welcome_index_path, class: 'main-title' %>
          <ul class="nav masthead-nav">
            <li><%= link_to 'Программирование',  programming_index_path %></li>
            <li><%= link_to 'Музыка',  music_index_path %></li>
            <li><%= link_to 'Литература',  literature_index_path %></li>
            <li><%= link_to 'Нигдея',  nowhereland_index_path %></li>
            <li><%= link_to 'Контакты',  contacts_index_path %></li>
            <li><%= link_to '<span class="glyphicon glyphicon-search"></span>'.html_safe,  "#" %></li>
          </ul>
        </div>
      </div>

      <!-- Begin page content -->
      <div class="container">
        <div class="inner cover">
          <%= yield %>
        </div>
      </div>

      <!-- Site footer -->
      <div class="footer mastfoot">
        <%= render 'shared/footer' %>
      </div>

    </div> <!-- /container -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script src="http://bootstrap-3.ru/assets/js/docs.min.js"></script>

  </body>
</html>

app/views/shared/_footer.html.erb
<p>
  2016 © Igor Klekotnev
</p>
<p>
  <a href="mailto:klekotnev@gmail.com?Subject=From wordside.ru" target="_top">
    Написать автору
  </a>
</p>

app/views/shared/_literature_nav.html.erb
<ul class="nav nav-pills nav-stacked">
<% locals[:sub_sections].sort.each do |sub| %>
  <li><%= link_to sub.title, action: sub.name %></li>
<% end %>
</ul>

app/views/shared/_music_nav.html.erb
<ul class="nav nav-pills nav-stacked">
<% locals[:sub_sections].sort.each do |sub| %>
  <li><%= link_to sub.title, action: sub.name %></li>
<% end %>
</ul>

app/views/shared/_nowhereland_nav.html.erb
<ul class="nav nav-pills nav-stacked">
<% locals[:sub_sections].sort.each do |sub| %>
  <li><%= link_to sub.title, action: sub.name %></li>
<% end %>
</ul>

app/views/shared/_programming_nav.html.erb
<ul class="nav nav-pills nav-stacked">
<% locals[:sub_sections].sort.each do |sub| %>
  <li><%= link_to sub.title, action: sub.name %></li>
<% end %>
</ul>

app/views/shared/_section_base.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-2">
      <% section_name  = locals[:section].name %>
      <% sub_sections  = locals[:sub_sections]  %>
      <%= render 'shared/' + section_name + '_nav', locals: { sub_sections: sub_sections } %>
    </div>
    <div class="col-md-10">
      <div class="container-fluid">
        <div class="row">
          <%= locals[:section].description.html_safe %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_sub_music_base.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-2">
      <% section_name = locals[:section].name %>
      <% sub_sections = locals[:sub_sections]  %>
      <% albums       = locals[:albums]  %>
      <%= render 'shared/' + section_name + '_nav', locals: { sub_sections: sub_sections } %>
    </div>
    <div class="col-md-8">
      <div class="container-fluid">
        <div class="row">
          <%= locals[:description].html_safe %>
        </div>
      </div>
    </div>
    <div class="col-md-2">
      <div class="container-fluid">
        <div class="row">
          <%= render 'shared/_albuls_list.html.erb', locals { albums: albums } %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_sub_section_base.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-2">
      <% section_name = locals[:section].name %>
      <% sub_sections  = locals[:sub_sections]  %>
      <%= render 'shared/' + section_name + '_nav', locals: { sub_sections: sub_sections } %>
    </div>
    <div class="col-md-10">
      <div class="container-fluid">
        <div class="row">
          <%= locals[:description].html_safe %>
        </div>
      </div>
    </div>
  </div>
</div>